# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.93</version>
#    <timestamp>2026-06-17T16:44:55.117Z</timestamp>
#    <hash>a9ce31c04339e109</hash>
# </meta>

neoforge:
  - "/^neoforge$/m"
forge:
  - "/^forge$/m"

1.21.x:
  - "/^1.21$/m"
1.20.x:
  - "/^1.20$/m"
1.19.x:
  - "/^1.19$/m"
