kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mc_version=1.21.1
neoforge_version=21.1.219

mod_id=tree_shapes
mod_version=0.0.0-dev
release_type=beta
mod_name=Treeshapes
mod_author=possible_triangle
mod_description=Adds more trunk & foliage placers

kotlin_forge_version=5.8.0

repository=pssbletrngle/treeshapes
modrinth_project_id=mB9gmqAh
maven_group=com.possible-triangle