# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.72</version>
#    <timestamp>2026-05-21T17:38:21.841Z</timestamp>
#    <hash>9d521ee415ea61ee</hash>
# </meta>

blank_issues_enabled: false
